py_library(
    name = "serve",
    srcs = ["serve.py"],
    visibility = ["//:__subpackages__"],
    deps = [":lazy_structure_parser"],
)

py_library(
    name = "lazy_structure_parser",
    srcs = ["lazy_structure_parser.py"],
    visibility = ["//:__subpackages__"],
)
