# Adapted from: https://github.com/pubref/rules_protobuf/blob/master/.travis.yml
name: Test Sifter

on: pull_request

jobs:
  test-sifter:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Build and test Sifter.
      run: |
        V=3.7.0
        OS=linux
        ARCH=x86_64
        GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
        GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
        CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci"
        CI_ARTIFACT="bazel--installer.sh"
        URL="$GH_BASE/$GH_ARTIFACT"
        echo $URL
        wget -O install.sh $URL
        chmod +x install.sh
        ./install.sh --user
        rm -f install.sh
        git clone https://github.com/95616ARG/bazel_python.git
        cd bazel_python
        echo y | ./setup_python.sh 3.7.4 $HOME/.bazel_python
        cd .. && rm -rf bazel_python
        /home/runner/bin/bazel test //...
